'use client'

import { useEffect, useMemo, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import type { Barber, Barbershop, Service } from '@/types/database'
import { CalendarIcon, ClockIcon, PinIcon, ScissorsIcon } from '@/components/icons'

export default function ShopPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter()
  const [shop, setShop] = useState<Barbershop | null>(null); const [barbers, setBarbers] = useState<Barber[]>([]); const [services, setServices] = useState<Service[]>([])
  const [barber, setBarber] = useState(''); const [service, setService] = useState(''); const [date, setDate] = useState(''); const [time, setTime] = useState('')
  useEffect(() => { Promise.all([supabase.from('barbershops').select('*').eq('id', id).single(), supabase.from('barbers').select('*').eq('barbershop_id', id), supabase.from('services').select('*').eq('barbershop_id', id)]).then(([a,b,c]) => { setShop(a.data); setBarbers(b.data ?? []); setServices(c.data ?? []) }) }, [id])
  const selected = useMemo(() => services.find(item => item.id === service), [services, service])
  function continueBooking() { if (!barber || !service || !date || !time) return; router.push(`/agendar/confirmar?barber=${barber}&service=${service}&starts=${encodeURIComponent(`${date}T${time}:00-03:00`)}`) }
  if (!shop) return <div className="card p-8 text-center muted">Carregando barbearia...</div>

  return <section><div className="card relative mb-6 overflow-hidden"><div className="h-56 bg-gradient-to-r from-[#1F4E79]/60 to-[#C0392B]/40 sm:h-72">{shop.photo_url ? <img className="h-full w-full object-cover" src={shop.photo_url} alt={shop.name}/> : <div className="flex h-full items-center justify-center"><ScissorsIcon className="h-20 w-20 text-[#D4A574]/70"/></div>}</div><div className="absolute inset-0 bg-gradient-to-t from-[#121212] via-transparent to-transparent"/><div className="absolute bottom-0 p-6 sm:p-8"><p className="eyebrow">Barbearia</p><h1 className="text-3xl font-bold sm:text-4xl">{shop.name}</h1><p className="mt-2 flex items-center gap-2 text-[#D8D8D8]"><PinIcon className="text-[#C0392B]"/>{shop.address} — {shop.city}</p></div></div>
    <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div><h2 className="mb-4 text-2xl font-bold">Escolha seu serviço</h2><div className="grid gap-3 sm:grid-cols-2">{services.map(item => <button type="button" onClick={() => setService(item.id)} className={`card p-5 text-left transition ${service === item.id ? 'border-[#D4A574] ring-2 ring-[#D4A574]/20' : 'hover:border-white/25'}`} key={item.id}><ScissorsIcon className="mb-3 text-[#D4A574]"/><b className="block text-lg">{item.name}</b><span className="muted mt-1 block text-sm">{item.duration_minutes} minutos</span><strong className="mt-3 block text-[#D4A574]">R$ {Number(item.price).toFixed(2)}</strong></button>)}</div>{!services.length && <div className="card p-6 muted">Esta barbearia ainda não cadastrou serviços.</div>}
      <h2 className="mb-4 mt-8 text-2xl font-bold">Escolha o barbeiro</h2><div className="flex flex-wrap gap-3">{barbers.map(item => <button type="button" onClick={() => setBarber(item.id)} className={`flex items-center gap-3 rounded-xl border p-3 text-left transition ${barber === item.id ? 'border-[#1F77B4] bg-[#1F4E79]/30' : 'border-white/10 bg-[#1E1E1E] hover:border-white/25'}`} key={item.id}>{item.photo_url ? <img className="h-11 w-11 rounded-full object-cover" src={item.photo_url} alt=""/> : <span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#2A2A2A]"><ScissorsIcon className="text-[#D4A574]"/></span>}<b>{item.name}</b></button>)}</div></div>
      <aside className="card h-fit p-6 lg:sticky lg:top-24"><p className="eyebrow">Reserva</p><h2 className="mt-1 text-2xl font-bold">Seu horário</h2><div className="mt-5 space-y-4"><label><span className="field-label">Data</span><div className="relative"><CalendarIcon className="absolute left-4 top-1/2 -translate-y-1/2 text-[#D4A574]"/><input className="field-with-icon" type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e => setDate(e.target.value)}/></div></label><label><span className="field-label">Horário</span><div className="relative"><ClockIcon className="absolute left-4 top-1/2 -translate-y-1/2 text-[#D4A574]"/><input className="field-with-icon" type="time" step="1800" value={time} onChange={e => setTime(e.target.value)}/></div></label>{selected && <div className="rounded-xl border border-[#D4A574]/25 bg-[#D4A574]/5 p-4 text-sm"><span className="muted">Selecionado</span><b className="mt-1 block">{selected.name} · {selected.duration_minutes} min</b></div>}<button className="btn-primary w-full" onClick={continueBooking} disabled={!barber || !service || !date || !time}>Continuar agendamento</button></div></aside></div>
  </section>
}
